### ISSUE TITLE
Dependency for Maven

### ISSUE THREAD

**Issue by DiukarevSergii** [nosoop/SteamTrade-Java#7]
Hi, 

I try use your library and used:
```
<dependency>
      <groupId>com.nosoop.steamtrade</groupId>
      <artifactId>SteamTrade-Java</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
```
but IntelliJ IDEA said that 

> dependency not found

Maybe you know what am I doing wrong?

**Comment by DiukarevSergii** [comment]
I don't how but now it works) So sorry about my question.

**Comment by Swingerok** [comment]
Same problem:"Unresolved dependency".
